config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get 'pages/welcome'

  resources :favorites
  resources :ratings
  resources :users do
    collection do
      get :search
      post :results
    end
  end
  resources :sitters
  resources :pets
  resources :sit_pets


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites
  def index
    @favorites = Favorite.all
  end

  # GET /favorites/1
  def show
    @favorite = Favorite.find(params[:id])
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
  end

  # POST /favorites
  def create
    @favorite = Favorite.new(favorite_params)

    if @favorite.save
      redirect_to @favorite, notice: 'Favorite was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /favorites/1
  def update
    @favorite = Favorite.find(params[:id])
    if @favorite.update(favorite_params)
      redirect_to @favorite, notice: 'Favorite was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /favorites/1
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to favorites_url, notice: 'Favorite was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def favorite_params
      params.require(:favorite).permit(:user_id, :sitter_id)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.haml
= form_for @favorite, html: { class: "form-horizontal", role: "form" } do |f|
  -if @favorite.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@favorite.errors.count, "error")} prohibited this favorite from being saved:"

      %ul
        - @favorite.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :user_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :user_id, class: 'form-control'
  .form-group
    = f.label :sitter_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :sitter_id, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/favorites/edit.html.haml
.page-header
  = link_to favorites_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @favorite, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing favorite

= render 'form'

app/views/favorites/index.html.haml
.page-header
  = link_to new_favorite_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Favorite
  %h1 Listing favorites

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th User
        %th Sitter
        %th{colspan: 3}

    %tbody
      - @favorites.each do |favorite|
        %tr
          %td= favorite.user_id
          %td= favorite.sitter_id
          %td
            = link_to favorite do
              %span.glyphicon.glyphicon-ok
          %td
            = link_to edit_favorite_path(favorite) do
              %span.glyphicon.glyphicon-pencil
          %td
            = link_to favorite, data: { confirm: 'Are you sure?' }, method: :delete do
              %span.glyphicon.glyphicon-remove

app/views/favorites/new.html.haml
.page-header
  = link_to favorites_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New favorite

= render 'form'

app/views/favorites/show.html.haml
.page-header
  = link_to favorites_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_favorite_path(@favorite), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show favorite

%dl.dl-horizontal
  %dt User:
  %dd= @favorite.user_id
  %dt Sitter:
  %dd= @favorite.sitter_id