config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get 'pages/welcome'

  resources :favorites
  resources :ratings
  resources :users do
    collection do
      get :search
      post :results
    end
  end
  resources :sitters
  resources :pets
  resources :sit_pets


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

end

app/models/sit_pet.rb
class SitPet < ApplicationRecord
  belongs_to :user, required: false
end

app/controllers/sit_pets_controller.rb
class SitPetsController < ApplicationController
  # GET /sit_pets
  def index
    @sit_pets = SitPet.all
  end

  # GET /sit_pets/1
  def show
    @sit_pet = SitPet.find(params[:id])
  end

  # GET /sit_pets/new
  def new
    @sit_pet = SitPet.new
  end

  # GET /sit_pets/1/edit
  def edit
    @sit_pet = SitPet.find(params[:id])
  end

  # POST /sit_pets
  def create
    @sit_pet = SitPet.new(sit_pet_params)

    if @sit_pet.save
      redirect_to @sit_pet, notice: 'Sit pet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sit_pets/1
  def update
    @sit_pet = SitPet.find(params[:id])
    if @sit_pet.update(sit_pet_params)
      redirect_to @sit_pet, notice: 'Sit pet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sit_pets/1
  def destroy
    @sit_pet = SitPet.find(params[:id])
    @sit_pet.destroy
    redirect_to sit_pets_url, notice: 'Sit pet was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def sit_pet_params
      params.require(:sit_pet).permit(:pet_kind, :breed, :size, :user_id)
    end
end

app/helpers/sit_pets_helper.rb
module SitPetsHelper
end

app/views/sit_pets/_form.html.haml
= form_for @sit_pet, html: { class: "form-horizontal", role: "form" } do |f|
  -if @sit_pet.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@sit_pet.errors.count, "error")} prohibited this sit_pet from being saved:"

      %ul
        - @sit_pet.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :pet_kind, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :pet_kind, class: 'form-control'
  .form-group
    = f.label :breed, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :breed, class: 'form-control'
  .form-group
    = f.label :dog_lg, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :dog_lg, class: 'form-control'
  .form-group
    = f.label :dog_md, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :dog_md, class: 'form-control'
  .form-group
    = f.label :dog_sm, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :dog_sm, class: 'form-control'
  .form-group
    = f.label :cat, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :cat, class: 'form-control'
  .form-group
    = f.label :other, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :other, class: 'form-control'
  .form-group
    = f.label :sitter_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :sitter_id, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/sit_pets/edit.html.haml
.page-header
  = link_to sit_pets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @sit_pet, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing sit_pet

= render 'form'

app/views/sit_pets/index.html.haml
.page-header
  = link_to new_sit_pet_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Sit pet
  %h1 Listing sit_pets

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Pet kind
        %th Breed
        %th Dog lg
        %th Dog md
        %th Dog sm
        %th Cat
        %th Other
        %th Sitter
        %th{colspan: 3}

    %tbody
      - @sit_pets.each do |sit_pet|
        %tr
          %td= sit_pet.pet_kind
          %td= sit_pet.breed
          %td= sit_pet.dog_lg
          %td= sit_pet.dog_md
          %td= sit_pet.dog_sm
          %td= sit_pet.cat
          %td= sit_pet.other
          %td= sit_pet.sitter_id
          %td
            = link_to sit_pet do
              %span.glyphicon.glyphicon-ok
          %td
            = link_to edit_sit_pet_path(sit_pet) do
              %span.glyphicon.glyphicon-pencil
          %td
            = link_to sit_pet, data: { confirm: 'Are you sure?' }, method: :delete do
              %span.glyphicon.glyphicon-remove

app/views/sit_pets/new.html.haml
.page-header
  = link_to sit_pets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New sit_pet

= render 'form'

app/views/sit_pets/show.html.haml
.page-header
  = link_to sit_pets_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_sit_pet_path(@sit_pet), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show sit_pet

%dl.dl-horizontal
  %dt Pet kind:
  %dd= @sit_pet.pet_kind
  %dt Breed:
  %dd= @sit_pet.breed
  %dt Dog lg:
  %dd= @sit_pet.dog_lg
  %dt Dog md:
  %dd= @sit_pet.dog_md
  %dt Dog sm:
  %dd= @sit_pet.dog_sm
  %dt Cat:
  %dd= @sit_pet.cat
  %dt Other:
  %dd= @sit_pet.other
  %dt Sitter:
  %dd= @sit_pet.sitter_id