config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get 'pages/welcome'

  resources :favorites
  resources :ratings
  resources :users do
    collection do
      get :search
      post :results
    end
  end
  resources :sitters
  resources :pets
  resources :sit_pets


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  RATINGS = [["", 0],["⭐", 1],["⭐⭐", 2],["⭐⭐⭐", 3],["⭐⭐⭐⭐", 4],["⭐⭐⭐⭐⭐", 5]]
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # GET /ratings
  def index
    @ratings = Star.all
    @ratings = @ratings.where(star: params[:star]) if params[:star].present?
  end

  # GET /ratings/1
  def show
    @rating = Rating.find(params[:id])
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  def create
    @rating = Rating.new(rating_params)

    if @rating.save
      redirect_to @rating, notice: 'Rating was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ratings/1
  def update
    @rating = Rating.find(params[:id])
    if @rating.update(rating_params)
      redirect_to @rating, notice: 'Rating was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ratings/1
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy
    redirect_to ratings_url, notice: 'Rating was successfully destroyed.'
  end

  private
    # Only allow a trusted parameter "white list" through.
    def rating_params
      params.require(:rating).permit(:star, :user_id, :sitter_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
  def star_rating(star)
    if star.nil? || star <= 0
      "NA"
    else
      "⭐" * [star,5].min
    end
  end
end

app/views/ratings/_form.html.haml
= form_for @rating, html: { class: "form-horizontal", role: "form" } do |f|
  -if @rating.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@rating.errors.count, "error")} prohibited this rating from being saved:"

      %ul
        - @rating.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :star, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :star, class: 'form-control'
  .form-group
    = f.label :user_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :user_id, class: 'form-control'
  .form-group
    = f.label :sitter_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.number_field :sitter_id, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/ratings/edit.html.haml
.page-header
  = link_to ratings_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @rating, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing rating

= render 'form'

app/views/ratings/index.html.haml
.page-header
  = link_to new_rating_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Rating
  %h1 Listing ratings

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Star
        %th User
        %th Sitter
        %th{colspan: 3}

    %tbody
      - @ratings.each do |rating|
        %tr
          %td= rating.star
          %td= rating.user_id
          %td= rating.sitter_id
          %td
            = link_to rating do
              %span.glyphicon.glyphicon-ok
          %td
            = link_to edit_rating_path(rating) do
              %span.glyphicon.glyphicon-pencil
          %td
            = link_to rating, data: { confirm: 'Are you sure?' }, method: :delete do
              %span.glyphicon.glyphicon-remove

app/views/ratings/new.html.haml
.page-header
  = link_to ratings_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New rating

= render 'form'

app/views/ratings/show.html.haml
.page-header
  = link_to ratings_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_rating_path(@rating), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show rating

%dl.dl-horizontal
  %dt Star:
  %dd= @rating.star
  %dt User:
  %dd= @rating.user_id
  %dt Sitter:
  %dd= @rating.sitter_id